import {
  Patient,
  UserProfile,
  VitalSign,
  Prescription,
  TestOrder,
  MedicineInventory,
  SurgeryRecord,
  TimelineEvent,
  HospitalNotification,
  Role,
} from "@/types/caresync";

export const DEMO_USERS: Record<Role, UserProfile> = {
  doctor: {
    id: "DOC-01",
    name: "Dr. Ananya Sharma",
    role: "doctor",
    title: "Senior Consultant Physician",
    department: "General Medicine & Critical Care",
    email: "ananya.sharma@caresync.health",
  },
  patient: {
    id: "CS-001",
    name: "Rajesh Sharma",
    role: "patient",
    title: "Patient (Ward 3B, Bed 12)",
    email: "rajesh.sharma@gmail.com",
  },
  nurse: {
    id: "NUR-01",
    name: "Priya Verma",
    role: "nurse",
    title: "Staff Nurse — Inpatient Ward 3B",
    department: "Inpatient Care",
    email: "priya.verma@caresync.health",
  },
  lab: {
    id: "LAB-01",
    name: "Neha Gupta",
    role: "lab",
    title: "Senior Lab Technologist",
    department: "Central Clinical Diagnostics",
    email: "neha.gupta@caresync.health",
  },
  pharmacy: {
    id: "PHARM-01",
    name: "Amit Singh",
    role: "pharmacy",
    title: "Chief Pharmacist",
    department: "Central Hospital Dispensary",
    email: "amit.singh@caresync.health",
  },
  receptionist: {
    id: "REC-01",
    name: "Rohan Mehta",
    role: "receptionist",
    title: "Front Desk & Patient Registrar",
    department: "Registration & Admissions",
    email: "rohan.mehta@caresync.health",
  },
};

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: "CS-001",
    name: "Rajesh Sharma",
    age: 54,
    gender: "Male",
    bloodGroup: "B+",
    phone: "+91 98765 43210",
    address: "42 Lotus Enclave, Indiranagar, Bengaluru",
    allergies: ["Penicillin", "Sulfa Drugs"],
    medicalHistory: ["Hypertension (5 yrs)", "Type 2 Diabetes", "Appendicitis"],
    status: "In Consultation",
    currentDepartment: "General Medicine",
    assignedDoctor: "Dr. Ananya Sharma",
    bedNumber: "Bed 12",
    roomNumber: "Ward 3B",
    registeredAt: "2026-09-15 08:30 AM",
  },
  {
    id: "CS-002",
    name: "Priya Verma",
    age: 31,
    gender: "Female",
    bloodGroup: "O+",
    phone: "+91 98451 23456",
    address: "108 Palm Grove, Koramangala, Bengaluru",
    allergies: ["Dust / Latex"],
    medicalHistory: ["Asthma (Mild)", "Hypothyroidism"],
    status: "Waiting",
    currentDepartment: "Outpatient Clinic",
    assignedDoctor: "Dr. Ananya Sharma",
    registeredAt: "2026-09-15 09:10 AM",
  },
  {
    id: "CS-003",
    name: "Amit Singh",
    age: 43,
    gender: "Male",
    bloodGroup: "A+",
    phone: "+91 97321 65498",
    address: "77 Greenwood Residency, HSR Layout, Bengaluru",
    allergies: ["None known"],
    medicalHistory: ["Acute Bronchitis"],
    status: "Diagnostics",
    currentDepartment: "Laboratory",
    assignedDoctor: "Dr. Ananya Sharma",
    registeredAt: "2026-09-15 09:25 AM",
  },
  {
    id: "CS-004",
    name: "Sunita Rao",
    age: 62,
    gender: "Female",
    bloodGroup: "AB+",
    phone: "+91 91234 56780",
    address: "15 Jasmine Heights, Whitefield, Bengaluru",
    allergies: ["Aspirin"],
    medicalHistory: ["Osteoarthritis", "Coronary Stent (2022)"],
    status: "Admitted",
    currentDepartment: "Cardiology & Recovery",
    assignedDoctor: "Dr. Ananya Sharma",
    bedNumber: "Bed 04",
    roomNumber: "Ward 2A",
    registeredAt: "2026-09-14 06:15 PM",
  },
];

export const INITIAL_VITALS: VitalSign[] = [
  {
    id: "VIT-001",
    patientId: "CS-001",
    temperature: "98.6 °F",
    bloodPressure: "128/84 mmHg",
    pulse: "76 bpm",
    spO2: "98%",
    recordedAt: "Today, 09:00 AM",
    recordedBy: "Priya Verma (Nurse)",
    notes: "Patient feels slight abdominal discomfort.",
  },
  {
    id: "VIT-002",
    patientId: "CS-001",
    temperature: "99.1 °F",
    bloodPressure: "132/86 mmHg",
    pulse: "80 bpm",
    spO2: "97%",
    recordedAt: "Today, 01:30 PM",
    recordedBy: "Priya Verma (Nurse)",
    notes: "Post-consultation checkup. Stable vitals.",
  },
  {
    id: "VIT-003",
    patientId: "CS-004",
    temperature: "98.4 °F",
    bloodPressure: "120/78 mmHg",
    pulse: "68 bpm",
    spO2: "99%",
    recordedAt: "Today, 10:15 AM",
    recordedBy: "Priya Verma (Nurse)",
    notes: "Morning recovery check.",
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: "RX-101",
    patientId: "CS-001",
    patientName: "Rajesh Sharma",
    doctorId: "DOC-01",
    doctorName: "Dr. Ananya Sharma",
    status: "Pending",
    createdAt: "Today, 09:45 AM",
    notes: "Take medicines after meals with warm water.",
    items: [
      {
        id: "RXI-1",
        medicine: "Paracetamol 500mg",
        dosage: "500mg",
        frequency: "1-0-1",
        duration: "5 days",
        instructions: "After breakfast and dinner",
      },
      {
        id: "RXI-2",
        medicine: "Pantoprazole 40mg",
        dosage: "40mg",
        frequency: "1-0-0",
        duration: "7 days",
        instructions: "Empty stomach before breakfast",
      },
      {
        id: "RXI-3",
        medicine: "Cefixime 200mg",
        dosage: "200mg",
        frequency: "1-0-1",
        duration: "5 days",
        instructions: "Antibiotic course. Complete full dosage.",
      },
    ],
  },
  {
    id: "RX-102",
    patientId: "CS-002",
    patientName: "Priya Verma",
    doctorId: "DOC-01",
    doctorName: "Dr. Ananya Sharma",
    status: "Dispensed",
    createdAt: "Today, 08:30 AM",
    dispensedAt: "Today, 08:50 AM",
    items: [
      {
        id: "RXI-4",
        medicine: "Montelukast + Levocetirizine",
        dosage: "10mg/5mg",
        frequency: "0-0-1",
        duration: "10 days",
        instructions: "Before bedtime",
      },
    ],
  },
];

export const INITIAL_TEST_ORDERS: TestOrder[] = [
  {
    id: "LAB-801",
    patientId: "CS-001",
    patientName: "Rajesh Sharma",
    doctorName: "Dr. Ananya Sharma",
    testName: "Complete Blood Count (CBC)",
    priority: "Urgent",
    status: "In Progress",
    orderedAt: "Today, 09:15 AM",
    results: [
      {
        parameter: "Hemoglobin (Hb)",
        value: "13.8",
        referenceRange: "13.0 - 17.0 g/dL",
        status: "Normal",
      },
      {
        parameter: "Total WBC Count",
        value: "11,200",
        referenceRange: "4,000 - 10,000 /uL",
        status: "High",
      },
      {
        parameter: "Platelet Count",
        value: "240,000",
        referenceRange: "150,000 - 450,000 /uL",
        status: "Normal",
      },
      { parameter: "Neutrophils", value: "74", referenceRange: "40 - 70 %", status: "High" },
    ],
    labNotes: "Mild leukocytosis noted, consistent with acute abdominal inflammation.",
  },
  {
    id: "LAB-802",
    patientId: "CS-003",
    patientName: "Amit Singh",
    doctorName: "Dr. Ananya Sharma",
    testName: "Chest X-Ray (PA View)",
    priority: "Routine",
    status: "Pending",
    orderedAt: "Today, 09:30 AM",
  },
  {
    id: "LAB-803",
    patientId: "CS-001",
    patientName: "Rajesh Sharma",
    doctorName: "Dr. Ananya Sharma",
    testName: "Fasting Blood Sugar & HbA1c",
    priority: "Routine",
    status: "Completed",
    orderedAt: "Today, 08:45 AM",
    completedAt: "Today, 10:15 AM",
    results: [
      {
        parameter: "Fasting Blood Glucose",
        value: "118",
        referenceRange: "70 - 99 mg/dL",
        status: "High",
      },
      { parameter: "HbA1c", value: "6.4", referenceRange: "< 5.7 %", status: "High" },
    ],
  },
  {
    id: "LAB-804",
    patientId: "CS-004",
    patientName: "Sunita Rao",
    doctorName: "Dr. Ananya Sharma",
    testName: "Lipid Profile",
    priority: "Routine",
    status: "Completed",
    orderedAt: "Yesterday, 07:00 PM",
    completedAt: "Today, 08:00 AM",
    results: [
      {
        parameter: "Total Cholesterol",
        value: "185",
        referenceRange: "< 200 mg/dL",
        status: "Normal",
      },
      { parameter: "Triglycerides", value: "142", referenceRange: "< 150 mg/dL", status: "Normal" },
      { parameter: "HDL Cholesterol", value: "48", referenceRange: "> 40 mg/dL", status: "Normal" },
    ],
  },
];

export const INITIAL_MEDICINES: MedicineInventory[] = [
  {
    id: "MED-1",
    name: "Paracetamol 500mg",
    category: "Analgesic / Antipyretic",
    stock: 450,
    unit: "Tablets",
    price: 15,
    status: "In Stock",
    reorder_level: 100,
  },
  {
    id: "MED-2",
    name: "Pantoprazole 40mg",
    category: "Antacid / PPI",
    stock: 320,
    unit: "Tablets",
    price: 85,
    status: "In Stock",
    reorder_level: 80,
  },
  {
    id: "MED-3",
    name: "Cefixime 200mg",
    category: "Antibiotic",
    stock: 85,
    unit: "Tablets",
    price: 140,
    status: "Low Stock",
    reorder_level: 100,
  },
  {
    id: "MED-4",
    name: "Amoxicillin + Clavulanic Acid 625mg",
    category: "Antibiotic",
    stock: 210,
    unit: "Tablets",
    price: 190,
    status: "In Stock",
    reorder_level: 60,
  },
  {
    id: "MED-5",
    name: "Metformin 500mg",
    category: "Antidiabetic",
    stock: 500,
    unit: "Tablets",
    price: 35,
    status: "In Stock",
    reorder_level: 120,
  },
  {
    id: "MED-6",
    name: "Telmisartan 40mg",
    category: "Antihypertensive",
    stock: 28,
    unit: "Tablets",
    price: 95,
    status: "Low Stock",
    reorder_level: 50,
  },
  {
    id: "MED-7",
    name: "Montelukast + Levocetirizine",
    category: "Antiallergic",
    stock: 175,
    unit: "Tablets",
    price: 110,
    status: "In Stock",
    reorder_level: 50,
  },
  {
    id: "MED-8",
    name: "Normal Saline (0.9% NaCl 500ml)",
    category: "IV Fluids",
    stock: 14,
    unit: "Bottles",
    price: 45,
    status: "Low Stock",
    reorder_level: 30,
  },
];

export const INITIAL_SURGERIES: SurgeryRecord[] = [
  {
    id: "SURG-01",
    patientId: "CS-001",
    patientName: "Rajesh Sharma",
    procedureName: "Laparoscopic Appendectomy",
    surgeon: "Dr. Ananya Sharma",
    anesthesiologist: "Dr. Vikram Seth",
    scheduledDate: "2026-09-15 02:30 PM (Today)",
    status: "Pre-Op",
    milestones: [
      { title: "Admission & Bed Assignment (Ward 3B)", status: "completed", timestamp: "08:30 AM" },
      { title: "Pre-operative Clinical Assessment", status: "completed", timestamp: "09:00 AM" },
      {
        title: "Required Diagnostic Tests (CBC & Blood Sugar)",
        status: "completed",
        timestamp: "10:15 AM",
      },
      {
        title: "Anesthesia Clearance & Consent Signed",
        status: "completed",
        timestamp: "11:30 AM",
      },
      { title: "Surgery Scheduled (OT Suite 2)", status: "completed", timestamp: "02:30 PM" },
      { title: "Surgery in Progress", status: "in_progress", timestamp: "02:45 PM" },
      { title: "Post-operative Monitoring & Recovery Care", status: "pending" },
      { title: "Attending Doctor Review & Rounds", status: "pending" },
      { title: "Discharge Summary & Prescription", status: "pending" },
    ],
    notes: "Elective laparoscopic procedure. Patient fasting since 06:00 AM.",
  },
];

export const INITIAL_TIMELINES: Record<string, TimelineEvent[]> = {
  "CS-001": [
    {
      id: "EV-1",
      patientId: "CS-001",
      title: "Patient Registered",
      department: "Reception",
      description: "Patient checked in at main lobby desk. UHID CS-001 created.",
      timestamp: "08:30 AM",
      actor: "Rohan Mehta (Receptionist)",
      status: "completed",
      iconType: "registration",
    },
    {
      id: "EV-2",
      patientId: "CS-001",
      title: "Initial Vitals Recorded",
      department: "Nursing",
      description: "BP: 128/84 mmHg, Temp: 98.6 °F, Pulse: 76 bpm, SpO2: 98%.",
      timestamp: "09:00 AM",
      actor: "Priya Verma (Nurse)",
      status: "completed",
      iconType: "nurse",
    },
    {
      id: "EV-3",
      patientId: "CS-001",
      title: "Doctor Consultation",
      department: "OPD / Consultation",
      description: "Evaluated for right lower quadrant tenderness. Suspected appendicitis.",
      timestamp: "09:15 AM",
      actor: "Dr. Ananya Sharma",
      status: "completed",
      iconType: "consultation",
    },
    {
      id: "EV-4",
      patientId: "CS-001",
      title: "Diagnostic Tests Ordered (CBC & Fasting Sugar)",
      department: "Laboratory",
      description: "Automated digital requisition forwarded to Central Clinical Lab.",
      timestamp: "09:20 AM",
      actor: "Dr. Ananya Sharma",
      status: "completed",
      iconType: "lab",
    },
    {
      id: "EV-5",
      patientId: "CS-001",
      title: "CBC & Glucose Reports Verified",
      department: "Laboratory",
      description: "Lab results uploaded. Leukocytosis detected (WBC 11,200).",
      timestamp: "10:15 AM",
      actor: "Neha Gupta (Lab Tech)",
      status: "completed",
      iconType: "lab",
    },
    {
      id: "EV-6",
      patientId: "CS-001",
      title: "Digital Prescription Generated",
      department: "OPD / Doctor",
      description:
        "3 medications prescribed (Paracetamol, Pantoprazole, Cefixime). Requisition routed to Pharmacy.",
      timestamp: "10:30 AM",
      actor: "Dr. Ananya Sharma",
      status: "completed",
      iconType: "pharmacy",
    },
    {
      id: "EV-7",
      patientId: "CS-001",
      title: "Admitted for Laparoscopic Surgery",
      department: "Surgery & Admissions",
      description: "Patient admitted to Ward 3B, Bed 12. OT Suite 2 booked.",
      timestamp: "11:30 AM",
      actor: "Rohan Mehta (Admissions)",
      status: "completed",
      iconType: "surgery",
    },
    {
      id: "EV-8",
      patientId: "CS-001",
      title: "Surgery in Progress (OT Suite 2)",
      department: "Operation Theatre",
      description: "Laparoscopic appendectomy initiated by surgical team.",
      timestamp: "02:45 PM",
      actor: "Dr. Ananya Sharma (Lead Surgeon)",
      status: "current",
      iconType: "surgery",
    },
    {
      id: "EV-9",
      patientId: "CS-001",
      title: "Post-Operative Monitoring & Recovery",
      department: "Nursing & Ward 3B",
      description: "Continuous monitoring of vitals, IV fluid management, and wound check.",
      timestamp: "Estimated 04:30 PM",
      actor: "Priya Verma (Staff Nurse)",
      status: "upcoming",
      iconType: "nurse",
    },
  ],
};

export const INITIAL_NOTIFICATIONS: HospitalNotification[] = [
  {
    id: "NOTIF-1",
    title: "New Diagnostic Order",
    message: "CBC requested for Rajesh Sharma (CS-001) by Dr. Ananya Sharma.",
    targetRole: "lab",
    patientId: "CS-001",
    timestamp: "10 mins ago",
    read: false,
    type: "order",
  },
  {
    id: "NOTIF-2",
    title: "Prescription Ready for Dispensing",
    message: "Prescription RX-101 for Rajesh Sharma sent to Central Dispensary.",
    targetRole: "pharmacy",
    patientId: "CS-001",
    timestamp: "25 mins ago",
    read: false,
    type: "prescription",
  },
  {
    id: "NOTIF-3",
    title: "Test Completed: CBC Report Available",
    message: "CBC report for Rajesh Sharma (CS-001) is uploaded and verified.",
    targetRole: "doctor",
    patientId: "CS-001",
    timestamp: "40 mins ago",
    read: true,
    type: "result",
  },
  {
    id: "NOTIF-4",
    title: "Surgery Milestone Update",
    message: "Rajesh Sharma: Laparoscopic Appendectomy started in OT-2.",
    targetRole: "nurse",
    patientId: "CS-001",
    timestamp: "1 hour ago",
    read: false,
    type: "surgery",
  },
];
