/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as SurgeryRouteImport } from './routes/surgery'
import { Route as DoctorConsultationRouteImport } from './routes/doctor.consultation'
import { Route as DoctorDashboardRouteImport } from './routes/doctor.dashboard'
import { Route as LabDashboardRouteImport } from './routes/lab.dashboard'
import { Route as NurseDashboardRouteImport } from './routes/nurse.dashboard'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as PharmacyDashboardRouteImport } from './routes/pharmacy.dashboard'
import { Route as ReceptionistDashboardRouteImport } from './routes/receptionist.dashboard'
import { Route as DoctorPatientIdRouteImport } from './routes/doctor.patient.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgeryRoute = SurgeryRouteImport.update({
  id: '/surgery',
  path: '/surgery',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultationRoute = DoctorConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DoctorRoute,
} as any)
const LabDashboardRoute = LabDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LabRoute,
} as any)
const NurseDashboardRoute = NurseDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => NurseRoute,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PatientRoute,
} as any)
const PharmacyDashboardRoute = PharmacyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PharmacyRoute,
} as any)
const ReceptionistDashboardRoute = ReceptionistDashboardRouteImport.update({
  id: '/receptionist/dashboard',
  path: '/receptionist/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientIdRoute = DoctorPatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reception': typeof ReceptionRoute
  '/surgery': typeof SurgeryRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/lab/dashboard': typeof LabDashboardRoute
  '/nurse/dashboard': typeof NurseDashboardRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reception': typeof ReceptionRoute
  '/surgery': typeof SurgeryRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/lab/dashboard': typeof LabDashboardRoute
  '/nurse/dashboard': typeof NurseDashboardRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/lab': typeof LabRouteWithChildren
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/reception': typeof ReceptionRoute
  '/surgery': typeof SurgeryRoute
  '/doctor/consultation': typeof DoctorConsultationRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/lab/dashboard': typeof LabDashboardRoute
  '/nurse/dashboard': typeof NurseDashboardRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/receptionist/dashboard': typeof ReceptionistDashboardRoute
  '/doctor/patient/$id': typeof DoctorPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/doctor'
    | '/lab'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/pharmacy'
    | '/reception'
    | '/surgery'
    | '/doctor/consultation'
    | '/doctor/dashboard'
    | '/lab/dashboard'
    | '/nurse/dashboard'
    | '/patient/dashboard'
    | '/pharmacy/dashboard'
    | '/receptionist/dashboard'
    | '/doctor/patient/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/doctor'
    | '/lab'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/pharmacy'
    | '/reception'
    | '/surgery'
    | '/doctor/consultation'
    | '/doctor/dashboard'
    | '/lab/dashboard'
    | '/nurse/dashboard'
    | '/patient/dashboard'
    | '/pharmacy/dashboard'
    | '/receptionist/dashboard'
    | '/doctor/patient/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/doctor'
    | '/lab'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/pharmacy'
    | '/reception'
    | '/surgery'
    | '/doctor/consultation'
    | '/doctor/dashboard'
    | '/lab/dashboard'
    | '/nurse/dashboard'
    | '/patient/dashboard'
    | '/pharmacy/dashboard'
    | '/receptionist/dashboard'
    | '/doctor/patient/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  LabRoute: typeof LabRouteWithChildren
  LoginRoute: typeof LoginRoute
  NurseRoute: typeof NurseRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  PharmacyRoute: typeof PharmacyRouteWithChildren
  ReceptionRoute: typeof ReceptionRoute
  SurgeryRoute: typeof SurgeryRoute
  ReceptionistDashboardRoute: typeof ReceptionistDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgery': {
      id: '/surgery'
      path: '/surgery'
      fullPath: '/surgery'
      preLoaderRoute: typeof SurgeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultation': {
      id: '/doctor/consultation'
      path: '/consultation'
      fullPath: '/doctor/consultation'
      preLoaderRoute: typeof DoctorConsultationRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/lab/dashboard': {
      id: '/lab/dashboard'
      path: '/dashboard'
      fullPath: '/lab/dashboard'
      preLoaderRoute: typeof LabDashboardRouteImport
      parentRoute: typeof LabRoute
    }
    '/nurse/dashboard': {
      id: '/nurse/dashboard'
      path: '/dashboard'
      fullPath: '/nurse/dashboard'
      preLoaderRoute: typeof NurseDashboardRouteImport
      parentRoute: typeof NurseRoute
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof PatientRoute
    }
    '/pharmacy/dashboard': {
      id: '/pharmacy/dashboard'
      path: '/dashboard'
      fullPath: '/pharmacy/dashboard'
      preLoaderRoute: typeof PharmacyDashboardRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/receptionist/dashboard': {
      id: '/receptionist/dashboard'
      path: '/receptionist/dashboard'
      fullPath: '/receptionist/dashboard'
      preLoaderRoute: typeof ReceptionistDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patient/$id': {
      id: '/doctor/patient/$id'
      path: '/patient/$id'
      fullPath: '/doctor/patient/$id'
      preLoaderRoute: typeof DoctorPatientIdRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorConsultationRoute: typeof DoctorConsultationRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorPatientIdRoute: typeof DoctorPatientIdRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorConsultationRoute: DoctorConsultationRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorPatientIdRoute: DoctorPatientIdRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface LabRouteChildren {
  LabDashboardRoute: typeof LabDashboardRoute
}

const LabRouteChildren: LabRouteChildren = {
  LabDashboardRoute: LabDashboardRoute,
}

const LabRouteWithChildren = LabRoute._addFileChildren(LabRouteChildren)

interface NurseRouteChildren {
  NurseDashboardRoute: typeof NurseDashboardRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseDashboardRoute: NurseDashboardRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface PatientRouteChildren {
  PatientDashboardRoute: typeof PatientDashboardRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientDashboardRoute: PatientDashboardRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface PharmacyRouteChildren {
  PharmacyDashboardRoute: typeof PharmacyDashboardRoute
}

const PharmacyRouteChildren: PharmacyRouteChildren = {
  PharmacyDashboardRoute: PharmacyDashboardRoute,
}

const PharmacyRouteWithChildren = PharmacyRoute._addFileChildren(
  PharmacyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  DoctorRoute: DoctorRouteWithChildren,
  LabRoute: LabRouteWithChildren,
  LoginRoute: LoginRoute,
  NurseRoute: NurseRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  PharmacyRoute: PharmacyRouteWithChildren,
  ReceptionRoute: ReceptionRoute,
  SurgeryRoute: SurgeryRoute,
  ReceptionistDashboardRoute: ReceptionistDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
